server:
  port: 7000


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
  application:
    name: cloud-gateway-eureka

eureka:
  client:
    service-url:
      defaultZone: http://192.168.20.132:8000/eureka/
    registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 12
    lease-renewal-interval-in-seconds: 4

logging:
  level:
    org.springframework.cloud.gateway: debug