server:
  port: 9000


spring:
  application:
    name: spring-cloud-producer

eureka:
  client:
    service-url:
      defaultZone: http://192.168.20.132:8000/eureka/
    registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 12
    lease-renewal-interval-in-seconds: 4

